GKE: add support for logging_config
kbst/terraform-kubestack pull request #295
Opened 2023-01-30 15:32 UTC by rzk

Adds support for setting `logging_config` configuration block.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#logging_config

2023-01-31 11:02 UTC, pst requested changes
Thanks for this contribution Dmitry. I left a small note about the default aspect. Let me know what you think.

2023-01-31 11:02 UTC, pst commented on google/_modules/gke/variables.tf
> +  default     = ["SYSTEM_COMPONENTS"]
If you set a default here, it will never be null in the for_each above. So in that case there's no poin in making it dynamic and do the for_each dance.

Question here is, currently I suppose the module doesn't set this at all. And then GKE picks some default. I generally like this as the default in Kubestack, because should upstream ever change their mind about that default, no changes to Kubestack are necessary and users always get the GKE that Google thinks is the best possible GKE.

So I think having the dynamic and for_each and removing the default on the variable is the way to go. So unless somebody sets logging_config, they get whatever is the GKE default. And for existing users this is a non-change.

2023-01-31 18:24 UTC, rzk commented on google/_modules/gke/variables.tf
> +  default     = ["SYSTEM_COMPONENTS"]
Removed `default`.

2023-02-02 13:19 UTC, pst commented on google/_modules/gke/variables.tf
> +  default     = ["SYSTEM_COMPONENTS"]
I've created a cluster with the current master. Then changed to your branch and ran a terraform plan.

It procudes this diff:

```
# module.gke_zero.module.cluster.google_container_cluster.current will be updated in-place
  ~ resource "google_container_cluster" "current" {
        id                          = "projects/terraform-kubestack-testing/locations/europe-west1/clusters/kbstacctest-ops-europe-west1"
        name                        = "kbstacctest-ops-europe-west1"
        # (27 unchanged attributes hidden)

      ~ logging_config {
          ~ enable_components = [
              - "SYSTEM_COMPONENTS",
              - "WORKLOADS",
            ]
        }

        # (18 unchanged blocks hidden)
    }
```

So it seems the approach with keeping the GKE default does not work here. In which case we will have to set defaults as part of the module. You can follow the approach used for the EKS module here: https://github.com/kbst/terraform-kubestack/blob/master/aws/cluster/configuration.tf#L54-L55 to keep it the same.

2023-02-03 12:53 UTC, merged